version: '3.8'

services:
  webapp:
    image: betterCinema/api   # Replace with the actual image name or build step
    build:
      context: ./Backend
      dockerfile: Dockerfile       # Dockerfile for the .NET app
    ports:
      - "5001:443"                  # Map host port 8080 to container port 80
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=mydb;User=root;Password=rootpassword;
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
      
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
        
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest  # SQL Server version
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Password" # Connect to SSMS using localhost,1433 as server name
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"                # Map host port 1433 to container port 1433
    volumes:
      - db_data:/var/opt/mssql     # Persistent storage for SQL Server data

volumes:
  db_data: