version: '3.4'

services:
  bettercinema.api:
    image: ${DOCKER_REGISTRY-}bettercinemaapi
    build:
      context: .
      dockerfile: src/BetterCinema.Api/Dockerfile

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest