# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln .
COPY src/. ./src/
COPY tests/. ./tests/
RUN file="$(ls -aLR .)" && echo $file
RUN dotnet restore

# copy everything else and build app
WORKDIR /source/src/BetterCinema.Api
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["dotnet", "BetterCinema.Api.dll"]