name: Deploy Bicep file
on:
  push:
    paths:
      - 'Infrastructure/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Recource Group
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./Infrastructure/resource-group.bicep
        parameters: 'resourceGroupName=${{ secrets.AZURE_RG }} resourceGroupLocation=${{ secrets.AZURE_LOCATION }}'
        failOnStdErr: false

    - name: Deploy Container Registry
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./Infrastructure/main.bicep
        parameters: 'acrName=betterCinemaCR'
        failOnStdErr: false

    - name: Deploy Azure SQL Server
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./Infrastructure/azure-sql-server.bicep
        parameters: 'administratorLogin=${{ secrets.DB_ADMINISTRATOR_LOGIN }} administratorLoginPassword=${{ secrets.DB_ADMINISTRATOR_PASSWORD }}'
        failOnStdErr: false
